# e2e/docker-compose.yml from repo
version: "3.8"
services:
  # this is the web application we are going to test
  converter:
    build: ./
    ports:
      - "4200:80"
  # Cypress container
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:9.3.1"
    depends_on:
      - converter
    environment:
      # pass base url to test pointing at the web application
      - cypress_baseUrl=http://converter:80
    # share the current folder as volume to avoid copying
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json
